### ISSUE TITLE
autocrafting: crafting 9 gold ingots to 9 gold nuggets

### ISSUE THREAD

**Issue by MrGeorgen** [DeadlyMC/QuickCarpet114#73]
quickcarpet 2.4.0
minecraft 1.16.3
malilib 1.16.3-0.10.0-dev.21+arne.1

I can craft 9 gold ingots to 9 gold nuggets.
![2020-10-19_20 09 44](https://user-images.githubusercontent.com/65063405/96495041-8e0b1100-1247-11eb-8474-f8ef2e5881c8.png)

**Comment by skyrising** [comment]
This behavior is caused by the hopper below and I currently don't plan on fixing it.
When a hopper is used as an item filter it will take one item from the inventory above, try to put it into each of the five slots and put it back if it can't. So as soon as you put in one ingot the hopper will take an item, which causes the crafting of nuggets to happen and put it back.

The solution here would be to replace the item filter with a system that unlocks the hopper below the crafting table when the comparator output of the crafting table is 15.

I believe 2No2Name's [hopperOptimizations](https://github.com/2No2Name/hopperOptimizations) mod also fixes this quirk in hopper behavior while keeping the desirable side effects (comparator updates)
