### ISSUE TITLE
minecraft crashes on start-up

### ISSUE THREAD

**Issue by beware08** [DeadlyMC/QuickCarpet114#77]
every time I open the game with quickcarpet in the mods folder, the game crashes. How can I solve this?

**Comment by joar** [comment]
@beware08 What kind of error message do you get?

**Comment by beware08** [comment]
@joar nothing. It just sends me back to the launcher with no error message whatsoever

**Comment by arceus6666** [comment]
@beware08 probably is due to incompatibility with other mods

**Comment by Ziadshoura** [comment]
First what mods are you using and second try to launch the game with only quick carpet and fabric api in your mods folder.

**Comment by KonnyK** [comment]
I have a similiar problem. I've tried out a few different things now:

starting fabric-loader-0.10.8-1.16.3 with only quickcarpet-2.4.0.jar in my mods folder the game runs, but it's vanilla

starting fabric-loader-0.10.8-1.16.4 with only quickcarpet-2.4.0.jar in my mods folder the game crashes when loading a world at the "saving world" step, it brings me back to the launcher with the error message: 
The game crashed whilst starting integrated server
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

starting fabric-loader-20w46a with only quickcarpet-2.4.0.jar in my mods folder the game crashes before the main menu with the error message:
An unknown problem occured and the game crashed. We're sorry.... Exit Code:0
(Probably because quickcarpet-2.4.0.jar is not for snapshots)

starting fabric-loader-20w46a with only quickcarpet-3.0.0-dev+a270655.jar in my mods folder the game runs but appears to be vanilla again

I also found out that having the fabric-api.jar for the correct minecraft version in my mods folder doesn't change these results. 
I really hope this helps I just want to be able to use autocrafting in my world. Preferably 1.16.4... :(

**Comment by beware08** [comment]
@arceus6666 @Ziadshoura thanks. It has been solved now. I also had regular Carpet in the mods folder, which the game didn't seem to be able to handle.

**Comment by Ziadshoura** [comment]
@KonnyK maybe it's a problem with your world try creating a brand new world and try that otherwise I don't know sorry

**Comment by skyrising** [comment]
@KonnyK There hasn't been a proper release for 1.16.4 yet, the current development builds of the master branch in actions (https://github.com/DeadlyMC/QuickCarpet114/actions/runs/387272860) are for 1.16.4
